Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
dim1 = []
dim2 = []
for image_filename in os.listdir('./images'):
    name, ext = os.path.splitext(image_filename)
    try:
        if not ext == '.xml':
            img = imread('./images/'+image_filename)
            d1,d2,color = img.shape
            dim1.append(d1)
            dim2.append(d2)
    except:
        print(image_filename)
        continue
------------------


[1;31m--------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                        Traceback (most recent call last)
Cell [1;32mIn [2], line 3[0m
[0;32m      1[0m dim1 [38;5;241m=[39m []
[0;32m      2[0m dim2 [38;5;241m=[39m []
[1;32m----> 3[0m [38;5;28;01mfor[39;00m image_filename [38;5;129;01min[39;00m os[38;5;241m.[39mlistdir([38;5;124m'[39m[38;5;124m./images[39m[38;5;124m'[39m):
[0;32m      4[0m     name, ext [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39msplitext(image_filename)
[0;32m      5[0m     [38;5;28;01mtry[39;00m:

[1;31mFileNotFoundError[0m: [WinError 3] El sistema no puede encontrar la ruta especificada: './images'

